Game Bar Samples Update
microsoft/XboxGameBarSamples pull request #125
Opened 2023-07-11 16:19 UTC by ranaway-ms

2023-07-13 18:55 UTC, vidager requested changes

2023-07-13 18:55 UTC, vidager commented on Samples/WidgetAdvSample/Widget1.cpp
> +        hstring isFullscreen = m_appTargetTracker.GetTarget().IsFullscreen() ? L"true" : L"false";
Should get target once and then grab properties off of it.

2023-08-07 22:04 UTC, vidager approved these changes

2023-08-30 17:55 UTC, ladebo approved these changes

2023-08-30 19:26 UTC, vidager approved these changes

2023-08-30 20:15 UTC, merged